### ISSUE TITLE
Prevent nully history events

### ISSUE THREAD

**Issue by philboeselager** [openlibraryenvironment/gokb#409]
The following log exception indicated that there are history events containing null `from` data.

```
java.lang.NullPointerException: Cannot get property 'name' on null object
    at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
    at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
    at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:46)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:299)
    at org.gokb.FTUpdateService$__tt__doFTUpdate_closure13.doCall(FTUpdateService.groovy:335)
    at org.gokb.FTUpdateService$__tt__doFTUpdate_closure13$doCall.call(Unknown Source)
    at org.gokb.FTUpdateService.$tt__updateES(FTUpdateService.groovy:456) 
```
    
While this exception is already prevented by 62ab33b8b23662d5610f84c62be0daf468224b58, the creation of such null data still has to be prevented. This is also holds for the `to` part.

Furthermore, existing "nully" history events should possibly be detected and cleaned up.

**Comment by croqueGrec09** [comment]
This is a thing I complain already for months. I had talk with @hornmo about empty dates in TitleHistoryEvent already in late '19 and in sync procedures, there are often records without dates.
